apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  ADMIN_USERNAME: "admin"
  ALLOWED_ORIGINS: '["*"]'
  LOG_FORMAT: "json"
  LOG_LEVEL: "INFO"
  NEW_RELIC_APP_NAME: "tech-challenge-oficina"
