from typing import Protocol
from uuid import UUID
from app.domain.entities.os import OrdemDeServico, StatusOS


class OSRepositoryPort(Protocol):
    """Persistência de Ordens de Serviço usada pelos casos de uso."""

    def buscar_por_id(self, os_id: UUID) -> OrdemDeServico | None: ...
    def buscar_para_escrita(self, os_id: UUID) -> OrdemDeServico: ...
    def listar(self, skip: int, limit: int, status: StatusOS | None) -> list[OrdemDeServico]: ...
    def adicionar(self, entidade) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def refresh(self, entidade) -> None: ...
